### ISSUE TITLE
anyOf

### ISSUE THREAD

**Issue by danziamo** [drom/resch#14]
```js
anyOf: [{
        properties: {
            veteranType: {
                enum: [''],
            }
        }
    }, {
        properties: {
            valid: {
                enum: [false],
            }
        }
    }],
    validityTrigger: true
```

**Comment by drom** [comment]
Looks like valid use case:
```js
{
  type: 'number',
  anyOf: [
    { multipleOf: 3 },
    { multipleOf: 5 }
  ]
}
```

**Comment by drom** [comment]
simplified implementation idea for `anyOf` and `allOf`:
 1. merge all `anyOf` sub-schema into single super-schema
 2. no selector needed.
 3. we can do nested `anyOf`s `anyOf`s
 4. use generic validator to check the original 'non-merged' schema.

**Comment by drom** [comment]
implemented:
 1. ignores `anyOf` for display
 2. fire `tv4` for schema validation of `object` with `anyOf`
